name: Deploy

on: workflow_dispatch

jobs:
  test:
    uses: k0swe/forester/.github/workflows/test-shared.yml@main

  firebase-deploy:
    name: Deploy to Firebase Hosting
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Read cached build artifacts
        id: read-cache
        uses: actions/cache@v3
        env:
          cache-name: cache-build-artifacts
        with:
          path: dist/
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ github.sha }}

      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

      - name: Tag as deployed
        run: |
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com
          git tag deployed --force
          git push --tags --force

      - name: Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@0.3.2
        with:
          args: >
            I just deployed Forester:
            ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
