name: Deploy

on: workflow_dispatch

jobs:
  test:
    uses: k0swe/forester/.github/workflows/test-shared.yml@main

  firebase-deploy:
    name: Deploy to Firebase Hosting
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Read cached build artifacts
        id: read-cache
        uses: actions/cache@v2
        env:
          cache-name: cache-build-artifacts
        with:
          path: dist/
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}

      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

      - name: Tag as deployed
        uses: xylo04/github-tag-action@force-tag
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: deployed
          tag_prefix: ''
          force: true
