name: Deploy

on:
  push:
    tags:
      - deploy

jobs:
  firebase-deploy:
    name: Deploy to Firebase Hosting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Cache emulator
        uses: actions/cache@v2
        env:
          cache-name: cache-firebase-emulator
        with:
          path: /home/runner/.cache/firebase/emulators
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/*.jar') }}

      - name: Setup node
        uses: actions/setup-node@master
        with:
          node-version: '10.x'

      - name: Install deps
        run: npm install

      - name: Test
        run: npm run test-ci

      - name: Compile
        run: npm run build-prod

      - name: Deploy to Firebase Hosting
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
