name: Deploy

on: workflow_dispatch

jobs:
  firebase-deploy:
    name: Deploy to Firebase Hosting
    runs-on: ubuntu-latest

    steps:
      - name: Test and Build
        uses: k0swe/forester/.github/workflows/test-shared.yml@main

      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

      - name: Tag as deployed
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: deployed
