name: CI

on:
  push:
    branches:
      - main

jobs:
  firebase-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
        name: Checkout
      - uses: actions/setup-node@master
        name: Setup node
        with:
          node-version: '10.x'
      - run: npm install
        name: Install deps
      - run: npm run build-prod
        name: Compile
      - uses: w9jds/firebase-action@master
        name: Deploy to Firebase Hosting
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
