name: Tag for deployment

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.5

      - name: Checkout
        uses: actions/checkout@v2

      - name: Bump version
        id: bump_version
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email ${GITHUB_ACTOR}@actions.github.com
          npm run tag-deploy
