name: Tag for deployment

on:
  workflow_dispatch:

jobs:
  tag_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Move tag
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email ${GITHUB_ACTOR}@actions.github.com
          git tag deploy -m deploy --force && git push --tags --force
