name: Test

on:
  push:
    branches-ignore:
      - 'renovate/**'
    tags-ignore:
      - deploy
  pull_request:
    branches:
      - '**'

jobs:
  firebase-deploy:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Test and Build
        uses: k0swe/forester/.github/workflows/test-shared.yml@main
