name: Test

on:
  push:
    branches-ignore:
      - 'renovate/**'
    tags-ignore:
      - deploy
  pull_request:
    branches:
      - '**'

jobs:
  firebase-deploy:
    name: Test and Compile
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup node
        uses: actions/setup-node@master
        with:
          node-version: '10.x'

      - name: Install deps
        run: npm install

      - name: Test
        run: npm run test-ci

      - name: Compile
        run: npm run build-prod
