name: Test

on:
  push:
    branches-ignore:
      - 'renovate/**'
    tags-ignore:
      - deploy
  pull_request:
    branches:
      - '**'

jobs:
  test:
    uses: k0swe/forester/.github/workflows/test-shared.yml@main
