name: npm update
on: workflow_dispatch

jobs:
  npm-update:
    name: npm update
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Cache node deps
        uses: actions/cache@v2
        env:
          cache-name: cache-node-deps
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}

      - name: npm update
        runs: -|
          npm install
          npm update

      - name: Commit and push
        uses: EndBug/add-and-commit@v8
        with:
          add: 'package*.json'
          message: 'npm update'
